version: '1'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: respondio_db
    ports:
      - "3306:3306"

  redis:
    image: redis:latest # Use the official Redis image
    ports:
      - '6379:6379' # Expose the default Redis port

  respondio-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: sh -c "npm run wait-db && npm run migrate && npm run start"
